apiVersion: v1
kind: Pod
metadata:
    name: firstpod
spec:
    containers:
        - image: nginx
          name: firstcontainer
          env:
            - name: myusername
              valueFrom:
                configMapKeyRef:
                  key: username
                  name: cm1
